name: local_community
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  circular_menu: ^4.0.0
  auto_size_text: ^3.0.0
  http: ^0.13.3
  google_sign_in: ^5.4.0
  postgres: ^3.4.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categories/
    - assets/appicon/logo.png
    - assets/placeholder.png

