name: local_community
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  circular_menu: ^4.0.0
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categories/
    - assets/appicon/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon/logo.png"  # Path to your icon image
